{
            {
                {// I piece
                    {e,e,e,e},
                    {F,F,F,F},
                    {e,e,e,e},
                    {e,e,e,e},
                },
                {
                    {e,e,F,e},
                    {e,e,F,e},
                    {e,e,F,e},
                    {e,e,F,e},
                },
                {
                    {e,e,e,e},
                    {e,e,e,e},
                    {F,F,F,F},
                    {e,e,e,e},
                },
                {
                    {e,F,e,e},
                    {e,F,e,e},
                    {e,F,e,e},
                    {e,F,e,e},
                }
            },
            {// left L piece
                {
                    {F,e,e,e},
                    {F,F,F,e},
                    {e,e,e,e},
                    {e,e,e,e},
                },
                {
                    {e,F,F,e},
                    {e,F,e,e},
                    {e,F,e,e},
                    {e,e,e,e},
                },
                {
                    {e,e,e,e},
                    {F,F,F,e},
                    {e,e,F,e},
                    {e,e,e,e},
                },
                {
                    {e,F,e,e},
                    {e,F,e,e},
                    {F,F,e,e},
                    {e,e,e,e},
                }
            },
            {//Right L piece
                {
                    {e,e,F,e},
                    {F,F,F,e},
                    {e,e,e,e},
                    {e,e,e,e},
                },
                {
                    {e,F,e,e},
                    {e,F,e,e},
                    {e,F,F,e},
                    {e,e,e,e},
                },
                {
                    {e,e,e,e},
                    {F,F,F,e},
                    {F,e,e,e},
                    {e,e,e,e},
                },
                {
                    {F,F,e,e},
                    {e,F,e,e},
                    {e,F,e,e},
                    {e,e,e,e},
                }
            },
            {//Square piece
                {
                    {e,F,F,e},
                    {e,F,F,e},
                    {e,e,e,e},
                    {e,e,e,e},
                },
                {
                    {e,F,F,e},
                    {e,F,F,e},
                    {e,e,e,e},
                    {e,e,e,e},
                },
                {
                    {e,F,F,e},
                    {e,F,F,e},
                    {e,e,e,e},
                    {e,e,e,e},
                },
                {
                    {e,F,F,e},
                    {e,F,F,e},
                    {e,e,e,e},
                    {e,e,e,e},
                }
            },
            {//S piece
                {
                    {e,F,F,e},
                    {F,F,e,e},
                    {e,e,e,e},
                    {e,e,e,e},
                },
                {
                    {e,F,e,e},
                    {e,F,F,e},
                    {e,e,F,e},
                    {e,e,e,e},
                },
                {
                    {e,e,e,e},
                    {e,F,F,e},
                    {F,F,e,e},
                    {e,e,e,e},
                },
                {
                    {F,e,e,e},
                    {F,F,e,e},
                    {e,F,e,e},
                    {e,e,e,e},
                }
            },
            {//T piece
                {
                    {e,F,e,e},
                    {F,F,F,e},
                    {e,e,e,e},
                    {e,e,e,e},
                },
                {
                    {e,F,e,e},
                    {e,F,F,e},
                    {e,F,e,e},
                    {e,e,e,e},
                },
                {
                    {e,e,e,e},
                    {F,F,F,e},
                    {e,F,e,e},
                    {e,e,e,e},
                },
                {
                    {e,F,e,e},
                    {F,F,e,e},
                    {e,F,e,e},
                    {e,e,e,e},
                }
            },
            {//Z piece
                {
                    {F,F,e,e},
                    {e,F,F,e},
                    {e,e,e,e},
                    {e,e,e,e},
                },
                {
                    {e,e,F,e},
                    {e,F,F,e},
                    {e,F,e,e},
                    {e,e,e,e},
                },
                {
                    {e,e,e,e},
                    {F,F,e,e},
                    {e,F,F,e},
                    {e,e,e,e},
                },
                {
                    {e,F,e,e},
                    {F,F,e,e},
                    {F,e,e,e},
                    {e,e,e,e},
                }
            },
        },
